DROP TABLE IF EXISTS PRODUCT;
  
CREATE TABLE PRODUCT (
  SKU INT AUTO_INCREMENT  PRIMARY KEY,
  category_id INT(11) DEFAULT NULL,
  size VARCHAR(25) DEFAULT NULL,
  color_id VARCHAR(25) DEFAULT NULL,
  brand_id VARCHAR(50) DEFAULT NULL,
  quantity INT(10) DEFAULT NULL,
  price INT(10) DEFAULT NULL
  
);

DROP TABLE IF EXISTS COLOR;
  
CREATE TABLE COLOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  COLOR VARCHAR(25) DEFAULT NULL
);

DROP TABLE IF EXISTS BRAND;
  
CREATE TABLE BRAND (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND VARCHAR(25) DEFAULT NULL
);

DROP TABLE IF EXISTS CATEGORY;
  
CREATE TABLE CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  CATEGORY VARCHAR(25) DEFAULT NULL
);